site_name: The Momentum Matrix
site_description: Strategic Growth Hacking on Your Terms
site_author: WentCloud
site_url: https://wentcloud.com

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  features:
    - navigation.footer

nav:
  - Home: index.md
  - The Momentum Matrix Pillars:
      - Purpose and Rationale: purpose-and-rationale.md
      - Impact: impact.md
      - People: people.md
      - Offerings: offerings.md
  - Implementation Strategy: implementation-strategy.md
  - Expected Results: expected-results.md
  - Commitment to Integrity: commitment-to-integrity.md
  - Conclusion: conclusion.md

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: http://linkedin.com/in/ryeieio/
    - icon: fontawesome/brands/github
      link: http://github.com/green-dino

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search


extra_css:
  - css/custom.css

extra_javascript:
  - js/custom.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js


# Metadata for SEO
extra:
  generator: false
  robots: index, follow
  keywords: growth hacking, strategic growth, leadership, high-performing teams, innovation, social impact, economic change
  description: The Momentum Matrix provides a strategic path for organizations to achieve scalable growth, increased impact, and enriched experiences—fueling momentum toward a sustainable and impactful future.